### ISSUE TITLE
[Bug]: Avoiding enchantment pulls items out from Corpses

### ISSUE THREAD

**Issue by SPYROHAWK** [Mrbysco/Hex#1]
### General Info

- [X] I am running a modpack
- [X] I can reproduce this issue consistently in single-player
- [X] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the mod

### Forge version

47.2.0

### Minecraft version

1.20.1

### Mod version

0.1.3

### Java version

No clue

### Issue Description

Weird interaction with the Corpse mod.

When dying, items enchanted with Avoiding get removed from the player’s corpse and teleport to world spawn, as if they had fallen into the void.

This is a big pain as what’s meant to be an item protection enchantment now effectively turns into curse of vanishing.

**Comment by Mrbysco** [comment]
Apparently I coded it specifically that way but never documented it did that

**Comment by SPYROHAWK** [comment]
Would it be possible to change that?

Or, another idea, add a config option in the config file to enable/disable each enchantment from showing up in-game so people can selectively change which ones they want to be available.

**Comment by Mrbysco** [comment]
Enchantments are registered and Forge does not want optional registering. The config can only load after the registering has finished

**Comment by Mrbysco** [comment]
I can add a config option to disable the death -> spawn functionality though as that's handled separately

**Comment by SPYROHAWK** [comment]
I don’t know about the amount of work required to do that and how many people are affected by this functionality, but for my situation at least that would be fantastic. It’s become a big concern for my group so a quick fix like that would be a lifesaver.

**Comment by Mrbysco** [comment]
New version is being uploaded
